# ----------------------------------------
# Database Configuration (PostgreSQL)
# ----------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_T9FaOjodM0PV
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-divine-mode-atkfj0r4-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

# Hibernate ORM Settings
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# ----------------------------------------
# AI Configuration (Gemini API)
# ----------------------------------------
quarkus.langchain4j.ai.gemini.api-key=AQ.Ab8RN6K2y8vuou4DIu2EnW5KQH1y-j-53_oVZkDzb8Lyj7CaTw
quarkus.langchain4j.ai.gemini.model-name=gemini-1.5-flash
google.vision.credentials.path=google-vision-key.json
# Log AI requests during dev
quarkus.log.category."io.quarkiverse.langchain4j".level=DEBUG

# ----------------------------------------
# HTTP Server & Memory Tuning
# ----------------------------------------
quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,OPTIONS,PUT,DELETE

# Restrict default heap size for constrained test box environments (4GB RAM total system memory)
%dev.quarkus.run.jvm.args=-Xmx1g -Xms512m